/**
 * Riferimenti Catalogo usati dalle regole Knowledge.
 * Evita stringhe magiche nelle rules.
 */

export const CATALOGO_IDS = Object.freeze({
  PUNTO_IMPIANTO: "PUNTO_IMPIANTO",
  PUNTO_DATI: "PUNTO_DATI",
  PUNTO_TV: "PUNTO_TV",
  QUADRO_12_MODULI: "QUADRO_12_MODULI",
  QUADRO_ELETTRICO: "QUADRO_ELETTRICO",
  CLIMA: "CLIMA",
  GATEWAY: "GATEWAY",
  BUS: "BUS",
  ALIMENTATORE: "ALIMENTATORE",
  DISTRIBUZIONE_LINEE_PIANO: "DISTRIBUZIONE_LINEE_PIANO",
  CANCELLO: "CANCELLO",
  ILLUMINAZIONE_ESTERNA: "ILLUMINAZIONE_ESTERNA",
  CITOFONO: "CITOFONO",
  VIDEOCITOFONO: "VIDEOCITOFONO",
  LINEA_INDUZIONE: "LINEA_INDUZIONE",
  ALLARME: "ALLARME",
  VIDEOSORVEGLIANZA: "VIDEOSORVEGLIANZA",
  FOTOVOLTAICO: "FOTOVOLTAICO",
  RICARICA_AUTO: "RICARICA_AUTO",
  IRRIGAZIONE: "IRRIGAZIONE",
});
